
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author devagrawal
 */
public class IssueBook extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        super("Issue Book");
        initComponents();
        conn=javaconnect.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        b_publisher = new javax.swing.JTextField();
        b_edition = new javax.swing.JTextField();
        b_name = new javax.swing.JTextField();
        bookid = new javax.swing.JTextField();
        b_price = new javax.swing.JTextField();
        b_pages = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        s_name = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        s_course = new javax.swing.JTextField();
        s_branch = new javax.swing.JTextField();
        s_year = new javax.swing.JTextField();
        s_semister = new javax.swing.JTextField();
        s_fname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        issuedate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("BOOK DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 183, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("STUDENT DETAILS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 183, -1, -1));

        jLabel3.setText("BOOK ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 269, -1, -1));

        jLabel4.setText("NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 311, -1, -1));

        jLabel5.setText("EDITION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 351, -1, -1));

        jLabel6.setText("PUBLISHER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 391, -1, -1));

        jLabel7.setText("PRICE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 431, -1, -1));

        jLabel8.setText("PAGES");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 471, -1, -1));

        b_publisher.setEditable(false);
        b_publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_publisherActionPerformed(evt);
            }
        });
        getContentPane().add(b_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 388, 190, -1));

        b_edition.setEditable(false);
        b_edition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editionActionPerformed(evt);
            }
        });
        getContentPane().add(b_edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 348, 190, -1));

        b_name.setEditable(false);
        getContentPane().add(b_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 308, 190, -1));
        getContentPane().add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 266, 190, -1));

        b_price.setEditable(false);
        getContentPane().add(b_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 428, 190, -1));

        b_pages.setEditable(false);
        b_pages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pagesActionPerformed(evt);
            }
        });
        getContentPane().add(b_pages, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 468, 190, -1));

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 265, -1, -1));

        jLabel9.setText("STUDENT ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 269, -1, -1));

        jLabel10.setText("NAME");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 311, -1, -1));

        jLabel11.setText("FATHER'S NAME");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 351, -1, -1));

        jLabel12.setText("COURSE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 391, -1, -1));

        jLabel13.setText("BRANCH");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 431, -1, -1));

        jLabel14.setText("YEAR");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 471, -1, -1));

        jLabel15.setText("SEMISTER");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 511, -1, -1));

        s_name.setEditable(false);
        s_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_nameActionPerformed(evt);
            }
        });
        getContentPane().add(s_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 308, 190, -1));
        getContentPane().add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 266, 190, -1));

        s_course.setEditable(false);
        s_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_courseActionPerformed(evt);
            }
        });
        getContentPane().add(s_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 388, 190, -1));

        s_branch.setEditable(false);
        getContentPane().add(s_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 428, 190, -1));

        s_year.setEditable(false);
        getContentPane().add(s_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 468, 190, -1));

        s_semister.setEditable(false);
        getContentPane().add(s_semister, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 508, 190, -1));

        s_fname.setEditable(false);
        getContentPane().add(s_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 348, 190, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setText("ISSUE BOOK");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 49, -1, -1));

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 265, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 183, -1, 360));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("DATE OF ISSUE:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 596, -1, -1));

        jButton3.setText("ISSUE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 683, -1, -1));

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 683, -1, -1));
        getContentPane().add(issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 596, 161, -1));

        jLabel18.setText("dd/mm/yyyy");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 625, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 770));

        setSize(new java.awt.Dimension(988, 813));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_editionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_editionActionPerformed

    private void b_pagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_pagesActionPerformed

    private void b_publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_publisherActionPerformed

    private void s_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_courseActionPerformed

    private void s_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_nameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home ob=new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql="select * from book where bookid=?"; 
        try
        {
                pst=conn.prepareStatement(sql);
                pst.setString(1,bookid.getText());
                rs=pst.executeQuery();
                if(rs.next())
                {
                    String add1=rs.getString("name");
                    b_name.setText(add1);
                    String add2=rs.getString("edition");
                    b_edition.setText(add2);
                    String add3=rs.getString("publisher");
                    b_publisher.setText(add3);
                    String add4=rs.getString("price");
                    b_price.setText(add4);
                    String add5=rs.getString("pages");
                    b_pages.setText(add5);
                    rs.close();
                    pst.close();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Book ID Not Found");
                }
                
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
        finally
        {
            try{
                rs.close();
                pst.close();
            }catch(Exception e)
                    {
                        
                    }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql="select * from student where studentid=?"; 
        try
        {
                pst=conn.prepareStatement(sql);
                pst.setString(1,studentid.getText());
                rs=pst.executeQuery();
                if(rs.next())
                {
                    String add1=rs.getString("name");
                    s_name.setText(add1);
                    String add2=rs.getString("fname");
                    s_fname.setText(add2);
                    String add3=rs.getString("course");
                    s_course.setText(add3);
                    String add4=rs.getString("branch");
                    s_branch.setText(add4);
                    String add5=rs.getString("year");
                    s_year.setText(add5);
                    String add6=rs.getString("semister");
                    s_semister.setText(add6);
                    rs.close();
                    pst.close();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Student ID Not Found");
                }
                
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
        finally
        {
            try{
                rs.close();
                pst.close();
            }catch(Exception e)
                    {
                        
                    }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql="insert into issue(bookid,name, edition, publisher, price, pages, studentid, sname, sfname, course, branch, year, semister, issuedate) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try
        {
            pst=conn.prepareStatement(sql);
            pst.setString(1, bookid.getText());
            pst.setString(2, b_name.getText());
            pst.setString(3, b_edition.getText());
            pst.setString(4, b_publisher.getText());
            pst.setString(5, b_price.getText());
            pst.setString(6, b_pages.getText());
            pst.setString(7, studentid.getText());
            pst.setString(8, s_name.getText());
            pst.setString(9, s_fname.getText());
            pst.setString(10, s_course.getText());
            pst.setString(11, s_branch.getText());
            pst.setString(12, s_year.getText());
            pst.setString(13, s_semister.getText());
            pst.setString(14, issuedate.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Book Issued");
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b_edition;
    private javax.swing.JTextField b_name;
    private javax.swing.JTextField b_pages;
    private javax.swing.JTextField b_price;
    private javax.swing.JTextField b_publisher;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField issuedate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField s_branch;
    private javax.swing.JTextField s_course;
    private javax.swing.JTextField s_fname;
    private javax.swing.JTextField s_name;
    private javax.swing.JTextField s_semister;
    private javax.swing.JTextField s_year;
    private javax.swing.JTextField studentid;
    // End of variables declaration//GEN-END:variables

    private void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
