
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author devagrawal
 */
public class RetrunBook extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form RetrunBook
     */
    public RetrunBook() {
        super("Return Book");
        initComponents();
        conn=javaconnect.ConnecrDb();
    }

    public void delete(){
        String sql="delete from issue where studentid=?";
        try
        {
            pst=conn.prepareStatement(sql);
            pst.setString(1, studentid1.getText());
            pst.execute();
            
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
    }
    
    public void update()
    {
        String sql="insert into returnbook(studentid, sname, sfname, scourse, sbranch, syear, ssemister, bookid, bname, bedition, bpublisher, bprice, bpages, doi, dor) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
        pst=conn.prepareStatement(sql);
        pst.setString(1, studentid1.getText());
        pst.setString(2, sname.getText());
        pst.setString(3, sfname.getText());
        pst.setString(4, scourse.getText());
        pst.setString(5, sbranch.getText());
        pst.setString(6, syear.getText());
        pst.setString(7, ssemister.getText());
        pst.setString(8, bookid.getText());
        pst.setString(9, bname.getText());
        pst.setString(10, bedition.getText());
        pst.setString(11, bpublisher.getText());
        pst.setString(12, bprice.getText());
        pst.setString(13, bpages.getText());
        pst.setString(14, doi.getText());
        pst.setString(15, dor.getText());
        pst.execute();
        JOptionPane.showMessageDialog(null, "Book Returned");
        
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
    }
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bpublisher = new javax.swing.JTextField();
        bedition = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        bookid = new javax.swing.JTextField();
        bprice = new javax.swing.JTextField();
        bpages = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sfname = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        studentid1 = new javax.swing.JTextField();
        scourse = new javax.swing.JTextField();
        sbranch = new javax.swing.JTextField();
        syear = new javax.swing.JTextField();
        ssemister = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        doi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        dor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("RETURN BOOK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 48, -1, -1));

        jLabel2.setText("BOOK ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 206, -1, -1));

        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 246, -1, -1));

        jLabel4.setText("EDITION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 286, -1, -1));

        jLabel5.setText("PUBLISHER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 326, -1, -1));

        jLabel6.setText("PRICE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 366, -1, -1));

        jLabel7.setText("PAGES");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 406, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("BOOK DETAILS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 151, -1, -1));

        bpublisher.setEditable(false);
        getContentPane().add(bpublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 323, 200, -1));

        bedition.setEditable(false);
        getContentPane().add(bedition, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 283, 200, -1));

        bname.setEditable(false);
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 243, 200, -1));

        bookid.setEditable(false);
        getContentPane().add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 203, 200, -1));

        bprice.setEditable(false);
        getContentPane().add(bprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 363, 200, -1));

        bpages.setEditable(false);
        bpages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpagesActionPerformed(evt);
            }
        });
        getContentPane().add(bpages, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 403, 200, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("STUDENT DETAILS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 151, -1, -1));

        jLabel10.setText("STUDENT ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 206, -1, -1));

        jLabel11.setText("NAME");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 246, -1, -1));

        jLabel12.setText("FATHER'S NAME");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 286, -1, -1));

        jLabel13.setText("COURSE");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 323, -1, -1));

        jLabel14.setText("BRANCH");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 366, -1, -1));

        jLabel15.setText("YEAR");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 406, -1, -1));

        jLabel16.setText("SEMISTER");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 446, -1, -1));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 496, -1, -1));

        sfname.setEditable(false);
        getContentPane().add(sfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 283, 200, -1));

        sname.setEditable(false);
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 243, 200, -1));
        getContentPane().add(studentid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 203, 200, -1));

        scourse.setEditable(false);
        getContentPane().add(scourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 323, 200, -1));

        sbranch.setEditable(false);
        getContentPane().add(sbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 363, 200, -1));

        syear.setEditable(false);
        syear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syearActionPerformed(evt);
            }
        });
        getContentPane().add(syear, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 403, 200, -1));

        ssemister.setEditable(false);
        getContentPane().add(ssemister, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 443, 200, -1));

        jLabel18.setText("DATE OF ISSUE");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        doi.setEditable(false);
        doi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doiActionPerformed(evt);
            }
        });
        getContentPane().add(doi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 180, -1));

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 206, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("DATE OF RETURN");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 508, -1, -1));
        getContentPane().add(dor, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 510, 200, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 249, -1, 191));

        jLabel20.setText("dd/mm/yyyy");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, -1, -1));

        jButton2.setText("RETURN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 601, -1, -1));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 601, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 680));

        setSize(new java.awt.Dimension(913, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void syearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_syearActionPerformed

    private void doiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doiActionPerformed

    private void bpagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpagesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql="select * from issue where studentid=?";
        try
        {
            pst=conn.prepareStatement(sql);
            pst.setString(1, studentid1.getText());
            rs=pst.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("sname");
                sname.setText(add1);
                String add2=rs.getString("sfname");
                sfname.setText(add2);
                String add3=rs.getString("course");
                scourse.setText(add3);
                String add4=rs.getString("branch");
                sbranch.setText(add4);
                String add5=rs.getString("year");
                syear.setText(add5);
                String add6=rs.getString("semister");
                ssemister.setText(add6);
                String add7=rs.getString("bookid");
                bookid.setText(add7);
                String add8=rs.getString("name");
                bname.setText(add8);
                String add9=rs.getString("edition");
                bedition.setText(add9);
                String add10=rs.getString("publisher");
                bpublisher.setText(add10);
                String add11=rs.getString("price");
                bprice.setText(add11);
                String add12=rs.getString("pages");
                bpages.setText(add12);
                String add13=rs.getString("issuedate");
                doi.setText(add13);
                
                rs.close();
                pst.close();
            }else
            {
                JOptionPane.showMessageDialog(null, "Book Not Issued With This Student ID");
            }
        }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home ob=new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        delete();
        update();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetrunBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetrunBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetrunBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetrunBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetrunBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bedition;
    private javax.swing.JTextField bname;
    private javax.swing.JTextField bookid;
    private javax.swing.JTextField bpages;
    private javax.swing.JTextField bprice;
    private javax.swing.JTextField bpublisher;
    private javax.swing.JTextField doi;
    private javax.swing.JTextField dor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField sbranch;
    private javax.swing.JTextField scourse;
    private javax.swing.JTextField sfname;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField ssemister;
    private javax.swing.JTextField studentid1;
    private javax.swing.JTextField syear;
    // End of variables declaration//GEN-END:variables
}
